In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

In [3]:
df = pd.read_csv('placement-dataset.csv')
df.head()

Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [4]:
df.shape

(100, 4)

In [5]:
df.dtypes

Unnamed: 0      int64
cgpa          float64
iq            float64
placement       int64
dtype: object

In [6]:
df['Unnamed: 0'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  100 non-null    int64  
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 3.2 KB


In [8]:
df = df.rename(columns= {'Unnamed: 0':'Student_id'})

In [9]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [10]:
df = df.drop('Student_id', axis= 1)

In [11]:
X = df.iloc[:, 0:-1].values
y = df.iloc[:, -1].values

In [12]:
X

array([[  6.8, 123. ],
       [  5.9, 106. ],
       [  5.3, 121. ],
       [  7.4, 132. ],
       [  5.8, 142. ],
       [  7.1,  48. ],
       [  5.7, 143. ],
       [  5. ,  63. ],
       [  6.1, 156. ],
       [  5.1,  66. ],
       [  6. ,  45. ],
       [  6.9, 138. ],
       [  5.4, 139. ],
       [  6.4, 116. ],
       [  6.1, 103. ],
       [  5.1, 176. ],
       [  5.2, 224. ],
       [  3.3, 183. ],
       [  4. , 100. ],
       [  5.2, 132. ],
       [  6.6, 120. ],
       [  7.1, 151. ],
       [  4.9, 120. ],
       [  4.7,  87. ],
       [  4.7, 121. ],
       [  5. ,  91. ],
       [  7. , 199. ],
       [  6. , 124. ],
       [  5.2,  90. ],
       [  7. , 112. ],
       [  7.6, 128. ],
       [  3.9, 109. ],
       [  7. , 139. ],
       [  6. , 149. ],
       [  4.8, 163. ],
       [  6.8,  90. ],
       [  5.7, 140. ],
       [  8.1, 149. ],
       [  6.5, 160. ],
       [  4.6, 146. ],
       [  4.9, 134. ],
       [  5.4, 114. ],
       [  7.6,  89. ],
       [  6

In [13]:
y

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x = sc.fit_transform(X)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state= 1)

In [16]:
X_train.shape

(80, 2)

In [17]:
X_test.shape

(20, 2)

In [18]:
y_train.shape

(80,)

In [19]:
y_test.shape

(20,)

In [20]:
ann = tf.keras.models.Sequential()

In [21]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid'))

In [24]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [25]:
ann.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
3/3 [==============================] - 1s 8ms/step - loss: 0.6798 - accuracy: 0.4750
Epoch 2/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6755 - accuracy: 0.4875
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6717 - accuracy: 0.4875
Epoch 4/100
3/3 [==============================] - 0s 1ms/step - loss: 0.6686 - accuracy: 0.4875
Epoch 5/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6653 - accuracy: 0.4875
Epoch 6/100
3/3 [==============================] - 0s 0s/step - loss: 0.6623 - accuracy: 0.5000
Epoch 7/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6592 - accuracy: 0.5125
Epoch 8/100
3/3 [==============================] - 0s 1ms/step - loss: 0.6560 - accuracy: 0.5375
Epoch 9/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6531 - accuracy: 0.5375
Epoch 10/100
3/3 [==============================] - 0s 0s/step - loss: 0.6499 - accuracy: 0.5375
Epoch 11/100
3/3 [=============

In [26]:
print(ann.predict(sc.transform([[6.6, 120.0]]))>0.5)

1/1 [==============================] - 0s 61ms/step
[[ True]]


In [27]:
y_pred = ann.predict(X_test)

y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 [==============================] - 0s 22ms/step
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]]


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)

print(cm)

accuracy_score(y_test, y_pred)

[[12  0]
 [ 2  6]]


0.9